name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo Hello, world!
      # Running Multi-Line Shell Commands
      - name: Run a multi-line script
        run: |
          echo "First output"
          echo "Second output"
